query AllActivitiesQuery {
  allActivities {
    id
    title
    _status
    price1
    price2
    price3
    price4
    _locales
    category
    order
    slug
    seo {
      description
      title
      image {
        url
      }
    }
    featuredImage {
      url
      title
      alt
      width
      height
    }
  }
}
